export const START_LOGIN = 'START_LOGIN';
export const FINISH_LOGIN = 'FINISH_LOGIN';
export const LOGOUT = 'LOGOUT';
export const HANDLE_LOGIN_ERROR = 'HANDLE_LOGIN_ERROR';
export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const MERGE_PAYMENTS = 'MERGE_PAYMENTS';
export const REMOVE_PAYMENT = 'REMOVE_PAYMENT';

export const MERGE_INTEGRATIONS = 'MERGE_INTEGRATIONS';
export const REMOVE_INTEGRATION = 'REMOVE_INTEGRATION';

export const MERGE_ACCOUNTS = 'MERGE_ACCOUNTS';
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';

export const MERGE_CUSTOMERS = 'MERGE_CUSTOMERS';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';

export const MERGE_ACCOUNT_PERMISSIONS = 'MERGE_ACCOUNT_PERMISSIONS';
export const REMOVE_ACCOUNT_PERMISSION = 'REMOVE_ACCOUNT_PERMISSION';

export const SET_ACTIVE_ACCOUNT_ID = 'SET_ACTIVE_ACCOUNT_ID';

export const SET_REPORT = 'SET_REPORT';

export const ADMIN_UPDATE_USER_ROLE = 'ADMIN_UPDATE_USER_ROLE';

export const MERGE_USERS = 'MERGE_USERS';
export const REMOVE_USER = 'REMOVE_USER';

export const CLEAR_SIGNUP_FORM = 'CLEAR_SIGNUP_FORM';
export const SET_SIGNUP_INVITATION = 'SET_SIGNUP_INVITATION';

export const OPEN_OVERLAY = 'OPEN_OVERLAY';
export const CLOSE_OVERLAY = 'CLOSE_OVERLAY';
