export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const START_LOGIN = 'START_LOGIN';
export const FINISH_LOGIN = 'FINISH_LOGIN';
export const HANDLE_LOGIN_ERROR = 'HANDLE_LOGIN_ERROR';
export const UPDATE_MY_PROFILE = 'UPDATE_MY_PROFILE';
